version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: subnetter_db
    environment:
      POSTGRES_DB: subnetter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - subnetter_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d subnetter"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: subnetter_api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SUBNETTER_APP_ENV: ${SUBNETTER_APP_ENV:-dev}
      SUBNETTER_DB_URL: ${SUBNETTER_DB_URL:-postgresql+asyncpg://postgres:postgres@db:5432/subnetter}
      SUBNETTER_JWT_SECRET: ${SUBNETTER_JWT_SECRET:-dev-not-secret}
    ports:
      - "8000:8000"
volumes:
  subnetter_db_data: {}
