version: "3.8"
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: ["9090:9090"]

  grafana:
    image: grafana/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    ports: ["3000:3000"]
    volumes:
      - ./ops/grafana/provisioning:/etc/grafana/provisioning